version: '3.7'


services:

  backend:
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - "./src:/opt/app/app/"

#  celery_worker:
#    volumes:
#      - "./src:/opt/app/app/"

  postgres:
    ports:
      - "5432:5432"

  redis:
    image: redis:6.0-alpine
    ports:
      - "6379:6379"
