version: '3.7'


services:

  backend:
    command: bash -c "uvicorn app.core.server:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - "./src:/opt/app"

  postgres:
    ports:
      - "5432:5432"

  redis:
    image: redis:6.0-alpine
    ports:
      - "6379:6379"
