version: '3.7'


services:

  backend:
    command: bash -c "aerich upgrade && uvicorn main:app --host 0.0.0.0 --port 8000 --workers"
    ports:
      - "8001:8000"

  postgres:
    ports:
      - "5442:5432"
